name       : haskell-regex-applicative-text
version    : 0.1.0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/regex-applicative-text-0.1.0.1/regex-applicative-text-0.1.0.1.tar.gz : b093051f80865d257da2ded8ad1b566927b01b3d2f86d41da2ffee4a26c4e2d9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Wrapped regex-applicative primitives to work with Text
description: |
    Wrapped regex-applicative primitives to work with Text
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-regex-applicative
    - haskell-text
setup      : |
    sed -i "s|4.10|4.12|g" regex-applicative-text.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
